name: Rename Project from Template

on:
  push:
    branches:
      - main

jobs:
  rename-project:
    runs-on: ubuntu-latest

    if: github.repository != 'Mkdda/repository-template' && github.run_number == 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rename project in settings.gradle.kts
        run: |
          
          REPO_NAME=$(echo "${{ github.event.repository.name }}")
          
          if [ -f "settings.gradle.kts" ]; then
            sed -i "s/rootProject.name = \".*\"/rootProject.name = \"$REPO_NAME\"/g" settings.gradle.kts
          elif [ -f "settings.gradle" ]; then
            sed -i "s/rootProject.name = \".*\"/rootProject.name = \"$REPO_NAME\"/g" settings.gradle
          fi

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git status
          # Solo hace commit si hubo cambios en los archivos
          git diff-index --quiet HEAD || git commit -m "chore: auto-rename project to ${{ github.event.repository.name }}"
          git push
